#!/bin/bash
source /usr/share/yunohost/helpers

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="${app}-graphql" --action="stop"

ynh_backup "$data_dir"
ynh_backup "$install_dir/.env"
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup "/etc/systemd/system/$app.service"
ynh_backup "/etc/systemd/system/${app}-graphql.service"

ynh_systemctl --service="${app}-graphql" --action="start"
ynh_systemctl --service="$app" --action="start"
