#!/bin/bash
source /usr/share/yunohost/helpers
source ./_common.sh

ynh_script_progression "Downloading Pantry Host..."
rm -rf "$install_dir"/*
git clone --depth 1 --branch "$upstream_branch" "$upstream_repo" "$install_dir"
rm -rf "$install_dir/.git"
chown -R "$app:$app" "$install_dir"

ynh_script_progression "Preparing persistent data..."
setup_persistent_paths

ynh_script_progression "Creating Pantry Host environment..."
ynh_config_add --template=".env" --destination="$install_dir/.env"
chmod 600 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

ynh_script_progression "Installing dependencies and building Pantry Host..."
install_dependencies_and_build

ynh_script_progression "Adding system configurations..."
ynh_config_add_systemd --service="${app}-graphql" --template="graphql.systemd.service"
ynh_config_add_systemd
ynh_config_add_nginx

yunohost service add "${app}-graphql" --description="Pantry Host GraphQL API" --log="systemd"
yunohost service add "$app" --description="Pantry Host web application" --log="systemd"

ynh_systemctl --service="${app}-graphql" --action="start" --log_path="systemd"
ynh_systemctl --service="$app" --action="start" --log_path="systemd"
