#!/bin/bash

source /usr/share/yunohost/helpers

ynh_script_progression "Restoring Pantry Host data and configuration..."

ynh_restore_file --origin_path="$data_dir"
ynh_restore_file --origin_path="$install_dir/.env"
ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
ynh_restore_file --origin_path="/etc/systemd/system/${app}-graphql.service"

chown -R "$app:$app" "$data_dir"
chown "$app:$app" "$install_dir/.env"
chmod 600 "$install_dir/.env"

systemctl daemon-reload
ynh_systemctl --service="${app}-graphql" --action="start" --log_path="systemd"
ynh_systemctl --service="$app" --action="start" --log_path="systemd"

ynh_script_progression "Restore of $app completed"
